- src/index.js
Checking that the payload data has been populated before adding it to the dispatched actions.
https://github.com/pburtchaell/redux-promise-middleware/issues/14
> checking payloads before adding to action

- src/index.js
in case the action creator promise resolves == null
https://github.com/pburtchaell/redux-promise-middleware/issues/20
> defaulting resolved to an empty object

- src/index.js
https://github.com/pburtchaell/redux-promise-middleware/issues/25
> Recalling dispatch so that middleware above in chain can be applied

- test/index.spec.js
Updated the tests to use our type suffixes and make sure things work as expected.
> updated tests to test for promises using promiseMiddlewares type suffixes

- test/index.spec.js
Started making some changes and my editor had red squares on the test file because of .eslintrc setup
> fixed linting error on tests for code editor happiness

- test/index.spec.js
> Typo in test name

- src/index.js
fixes https://github.com/pburtchaell/redux-promise-middleware/issues/51
> fixed Object.assign issue in react-native

- examples/README.md
The link to issue #33 was incorrect and is fixed by this commit
> fix issue link in README

- docs/guides/global-handling.md
Hey @pburtchaell, I've developed a [Loading Bar](https://github.com/mironov/react-redux-loading-bar) component that works great with `redux-promise-middleware` and might be helpful to others. What do you think about including it in the guides as an example?
> Add Loading Bar middleware as an example of global handling of actions

- src/index.js
- test/index.spec.js
> Reject promise with instance of Error

- package.json
- src/index.js
- test/index.spec.js
> Return original promise

- .gitignore
- src/index.js
- test/index.spec.js
> Throw original error when rejection reason instance of Error

- docs/guides/chaining-actions.md
- package.json
- src/index.js
- test/index.spec.js
See: https://github.com/pburtchaell/redux-promise-middleware/pull/101.
Resolves: #104.
> Rethrow originally caught error in handleReject

- README.md
Because first thing is "Introduction"
> Swat "Introduction" and "Guides"

- src/index.js
- test/index.spec.js
Resolves #159 and reverts the changes made in #126 (released in 4.3.0).
> Revert Version 4.3.0

- docs/README.md
- docs/guides/custom-separators.md
- src/index.js
- test/index.spec.js
> Custom separators for action types

- docs/README.md
- docs/guides/custom-delimiters.md
Connect https://github.com/pburtchaell/redux-promise-middleware/issues/197.
> Update Custom Type Delimiter Docs

- .travis.yml
Changes:
- Updates Node version for Travis CI, running parallel tests for v8.9.0 and the latest release
> Update Node version 

- .github/CONTRIBUTING.md
- package-lock.json
- package.json
- yarn.lock
Changes:
- Adds Redux 4 to peer dependencies
- Adds `yarn generate-lockfile` script to keep yarn.lock and package-lock.json in sync
- Bumps to version 5.1.0 for npm
Connect #205.
> Implement Support for Redux 4

- docs/guides/rejected-promises.md
Updated to https://github.com/pburtchaell/redux-promise-middleware/tree/master/examples/catching-errors-with-middleware/middleware.js
Hello! :wave: 
This template enables you to open an issue that is valuable for you, the project, and the GitHub community. :two_hearts:
Before submitting an issue, please:
1. Agree the [Code of Conduct](/.github/CODE_OF_CONDUCT.md).
2. Read the [Contributing Guide](/.github/CONTRIBUTING.md).
If you are new to open source, check out this 38 minute course on [how to contribute to open source on GitHub](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github). It's free! :smile:
---
Before submitting a pull request, please make sure the following is done:
1. Add tests for new functionality or bug fixes, following the …
> Update link to middleware example

- docs/guides/custom-suffixes.md
- docs/introduction.md
> Revert v6 Documentation

- docs/upgrading/v6.md
> Fix typo in upgrade docs

- src/index.d.ts
Cutting my teeth on TypeScript and writing type definition files. I welcome any and all feedback.
> Fix TypeScript ActionType definition (#241)

- README.md
> Remove double "a"

- src/index.js
Hello! :wave: 
This PR just update outdated example for custom types.
> Update example for custom types

- docs/README.md
- docs/guides/passing-extra-values-to-reducer.md
Hello! :wave: 
This template enables you to open an issue that is valuable for you, the project, and the GitHub community. :two_hearts:
Before submitting an issue, please:
1. Agree the [Code of Conduct](/.github/CODE_OF_CONDUCT.md).
2. Read the [Contributing Guide](/.github/CONTRIBUTING.md).
If you are new to open source, check out this 38 minute course on [how to contribute to open source on GitHub](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github). It's free! :smile:
---
Before submitting a pull request, please make sure the following is done:
1. Add tests for new functionality or bug fixes, following the [red/green/refactor method](https://en.wikipedia.org/wiki/Test-driven_development#Development_style)
2. Ensure all tests pass: `npm test`
3. Update …
> Document the `meta` key
