- src/index.js
It may be nice that the middleware adds "error: true" to the action in case of error. See https://github.com/acdlite/flux-standard-action
> Add error parameter to action in case of error

- README.md
- src/index.js
- src/isPromise.js
This moves the promise into the payload option to also allow passing the data object. This breaks the API, up to you how you want to handle that. I can either add support for the both scenarios or we can drop the previous method.
> Add optimistic update capability

- .gitignore
- README.md
- package.json
- src/index.js
Resolves #1.
Automatically assumes promise types of PENDING, FULFILLED, REJECTED.
Initial action now only needs to contain a single type.
Can customise the types at the middleware level:
```js
applyMiddleware(
promiseMiddleware({
promiseTypes: ['WAIT', 'YAY', 'BUGGER']
})
```
breaking change: when adding the middleware, it must be invoked even if you don't supply custom types:
```js
applyMiddleware(
promiseMiddleware()
...
// defaults to PENDING, FULFILLED, REJECTED
```
or override both at dispatch with the same payload as before, just add the types array to you meta object:
```js
dispatch({
type, payload, meta: {
promiseTypes: [ 'MAYBE', 'AWESOME', '*!@£' ]
}
})
```
> Default promise types

- src/index.js
When the promise resolves an object with a `meta` property,
this middleware will merge the resolved object into the fulfilled action and ignore the original meta
instead of the existing functionality of supplying the resolved object as just the payload and keeping the original meta
e.g.
Current behaviour is still preserved
```js
function myActionCreator(){
return {
type: 'ACTION',
payload: {
promise: Promise.resolve({ foo: 'bar' }) // resolve payload
},
meta: { herp: 'derp' }
}
}
/*
will eventually dispatch
{
type: 'ACTION_FULFILLED',
payload: { foo: 'bar' },
meta: { herp: 'derp' }
}
*/
```
But now can overwrite previous meta:
```js
function myActionCreator(){
return {
type: 'ACTION',
payload: {
promise: Promise.resolve({ // resolve full action
payload: {foo: 'bar'}, // note payload here …
```
> added customisable payload for promise resolution to fulfilled action

- src/index.js
After replacing the next calls with dispatch, the resolved payload can go through the whole middleware stack which is cool
```js
const action = () => ({
type: "FOO",
payload: {
promise: Promise.resolve({ payload: 'goes through middleware earlier in stack' })
}
})
```
But we assume these resolved values are either a payload or an action, so this change also checks for thunks or well... functions... if we find a function has been resolved, we dispatch it.. instead of only checking for payload or meta and then trying to dispatch the resolved value as a payload.
So now this should work too:
```js
const action = () => ({
type: "FOO",
payload: {
promise: Promise.resolve((dispatch, getState) => { // resolve a thunk!
dispatch({ payload: 'goes through middleware earlier in stack' })
dispatch({ …
```
> added check for thunk before resolving as payload

- src/index.js
Previous update to 2.2.2 was actually broken.. my mistake! Was attempting to merge the thunk function into the object with type! Arg!
This PR fixes that logic and also adds the same process to REJECT actions.
One down side, when your promise resolves a thunk, you need to manually add the action.type to the object you dispatch.
> correctly checking for thunk and doing same for reject

- src/index.js
as discussed in https://github.com/pburtchaell/redux-promise-middleware/pull/31#issuecomment-160353593
I've also made the checks more explicit with bang bang.
Tested it locally on a project and all works fine, wasn't sure whether to refactor the resolve/reject blocks down as they're basically the same now.
We should really write more tests for all these use-cases but I'm just too lazy right now!
> bind thunk to action when resolving thunk and made checks more explicit

- src/index.js
Redux [docs](http://redux.js.org/docs/api/Store.html#dispatch) state that store.dispatch should return the dispatched action.
So we should respect that API and return the dispatched action.
This raises a question around whether we should return the originally dispatched action created by the user, or our first `_PENDING` action -- as that's what gets passed through the chain. Also, other middleware may change this action and we should be returning their modifications... The standard is `return next(action)`... But this causes problems, as it doesn't allow a consumer to gain access to the later dispatched actions from the promise.
This PR now has our middleware return the original action that a consumer dispatches when our middleware intervenes. We also modify the promise contained in the …
> Returning action from middleware

- .npmignore
`redux-promise-middleware@3.0.1` has `node_modules` directory published inside it (which includes `history@2.0.1`). This causes an issue when trying to `npm shrinkwrap`: 
`extraneous: history@2.0.1 /Users/rotemm/git/github/wix-one-app/node_modules/redux-promise-middleware/node_modules/history`
> updated .npmignore to exclude node_modules

- package.json
- src/index.js
- webpack.config.js
Add UMD (Universal Module Definition) build tasks.
Implementation adapted from reactjs/react-router-redux@ad0d41d.
Modified module definition to work around webpack/webpack#706.
Thanks for considering this!
> Add UMD build tasks

- src/index.js
Using this syntax makes the import syntax less ambiguous for certain transpilers (i.e. typescript). It also makes declaring type defintions possible while still using es6 import syntax. Therefore TS users can write:
```typescript
import reduxPromiseMiddleware from 'redux-promise-middleware';
```
as opposed to:
```typescript
import reduxPromiseMiddleware = require('redux-promise-middleware')
```
Even better, there is no change for Babel users! Only enhancements for TS users.
> Use default export syntax for better compatibility with typescript

- src/index.js
This might be dumb edit, but I think keeping the ternary operators on a single line makes it a lot more readable. I thought about throwing in some extra parens as well to make it more obvious that you're assigning the properties of each resulting object into the return object and making the `...!!` a little more distinct as _two_ operations, because as an intermediate dev this threw me for a minutes. 
`...(!!meta ? { meta } : {}),`
vs. 
`...!!meta ? { meta } : {},`
Not sure if 'readability for average joes' is something you'd care about spending a few extra characters on though.
> Keep Ternary Operators on Single Line

- src/index.js
- test/index.spec.js
When a Promise resolves with a value of `0` or `false`, include that value as the `payload` property of the `FULFILLED` action.
The existing code omits the payload if it is any “falsy” value, which includes `null`, `undefined`, `0`, and `false`.
With this change, `null` and `undefined` payloads are still omitted, but `0` and `false` payloads are passed along with the `FULFILLED` action.
A slightly more idiomatic check for a `null` or `undefined` payload would be `newPayload == null`, but that is disallowed by the lint configuration.
I’ve added new specs for these cases, but they’re very similar to each other and have a fair bit of duplication with the `null` spec.  I wasn’t sure what you might want to do to clean that up.
> Allow payloads of `0` or `false`

- docs/guides/rejected-promises.md
I tried using a middleware to log all unhandled promises, and although it's clear now that I've stopped and thought about it, it took me a little while to realize that the middleware fired before the action creators did (so it couldn't know what was handled and what wasn't). My solution was to use a browser / Promises library "unhandledrejection" event.
This PR adds a bit of info about these alternatives and also tries to clarify a bit regarding redux-promise-middleware ("the middleware") versus custom error-handling middleware that the developer adds ("a middleware").
Feedback welcome.
> Add unhandledrejection option

- docs/guides/optimistic-updates.md
The docs previously seemed to indicate that the action dispatched for `FOO_PENDING` would have a `data` key nested under `payload`, whereas the `payload` key actually references `data` from the original action directly.
> Update action description for optimistic updates example

- src/index.js
- test/index.spec.js
Falsy data (e.g., `data: 0`) and falsy meta properties aren't preserved by the middleware, even though FSA allows payload and meta to be anything, due to the use of `!!data` and `!!meta`.  This commit fixes this by changing the handling to a more restrictive `!== undefined`.
> Fix handling of falsy data and meta

- docs/introduction.md
- src/index.js
- test/index.spec.js
You can now import the (currently three) default promise status:
```javascript
import { DEFAULT_PENDING, DEFAULT_FULFILLED, DEFAULT_REJECTED } from 'redux-promise-middleware'
```
Issue [#143](https://github.com/pburtchaell/redux-promise-middleware/issues/143).
> Export default promise status

- src/index.js
Allows browsers to import index.js and have dependencies resolve by relative path.
Closes #178
> Adds file extension to isPromise import

- .eslintrc
- docs/guides/async-await.md
- docs/guides/dispatching-promises.md
- docs/guides/reducers.md
- src/index.js
- test/index.spec.js
This PR develops the async/await implementation from PR #176. 
Changes:
- Adds support for optimistic data with async/await (with a test)
- Adds more comprehensive code comments
- Adds new names for the async/await tests
- Updates [how a promise is determined](https://github.com/pburtchaell/redux-promise-middleware/blob/2c540b0bf1b02e4c197e7b019894bb0b12861f65/src/index.js#L42-L84), with the aim of being more concise
Resolves #175.
> Develop Async/Await Support

- docs/introduction.md
- index.d.ts
- src/index.js
Create Typescript Definitions.
There already exists one under `@types/`, but that one was not updated for a while and does not match the implementation. It also doesn't include types for `PENDING`/`FULFILLED`/`REJECTED` consts.
> Create Typescript Definitions

- docs/guides/custom-suffixes.md
- docs/introduction.md
- examples/catching-errors-with-middleware/store.js
- examples/catching-errors/store.js
- examples/using-promise-actions/store.js
- examples/using-promise-all/store.js
- examples/using-promise-middleware/store.js
- src/index.js
- test/module.spec.js
- test/utils/createStore.js
Hello! :wave: 
Re-opening a PR for issue #219.
- Refactor public API to support a default config middleware and the ability to configure the middleware. This is more in line with other middlewares.
- Move current API to `createPromise` function
- Default export a function with default configuration
Default API:
```js
import thunk from 'redux-thunk';
import promise from 'redux-promise-middleware';
import logger from 'redux-logger';
const store = createStore(reducers, null, applyMiddleware(
thunk,
promise,
logger,
));
```
Custom middleware API:
```js
import thunk from 'redux-thunk';
import { createPromise } from 'redux-promise-middleware';
import { createLogger } from 'redux-logger';
const store = createStore(reducers, null, applyMiddleware(
thunk,
createPromise(myConfigObject), …
```
> Refactor Public API

- .npmignore
- package.json
Includes `index.d.ts` when publishing to npm.
Connect #236.
> Fix npmignore for TS definitions

- docs/guides/reducers.md
Correct import is `ActionType` but `ActionTypes` was being used.
Hello! :wave: 
This template enables you to open an issue that is valuable for you, the project, and the GitHub community. :two_hearts:
Before submitting an issue, please:
1. Agree the [Code of Conduct](/.github/CODE_OF_CONDUCT.md).
2. Read the [Contributing Guide](/.github/CONTRIBUTING.md).
If you are new to open source, check out this 38 minute course on [how to contribute to open source on GitHub](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github). It's free! :smile:
---
Before submitting a pull request, please make sure the following is done:
1. Add tests for new functionality or bug fixes, following the [red/green/refactor method](https://en.wikipedia.org/wiki/Test-driven_development#Develo …
> Fix typo in reducers guide

- src/index.js
Switched from psb.codes to psb.design domain name.
Connect #251.
> Update Upgrade Guide URL

- docs/guides/rejected-promises.md
The second `dispatch` is not needed and will throw a Type Error.
> Fix the example

- src/index.js
The current solution is not really working since after `webpack` replacement we end up with:
```
if (process && process.env && (false || 'test')) {
```
whitch is alway `true` and this part of code is never removed from production build.
> Fix removing warning from production build

- docs/guides/chaining-actions.md
I had an issue with my test
store.dispatch() wasn't tenable.
As we can see from  redux-thunk documentation https://github.com/reduxjs/redux-thunk, 
there is no obligation to return inner dispatch .
So I just wanted to clarify that in combination of 2 libraries it becomes a must.
It is not trivial to return the payload's promise as dispatch return value, so I just wanted to clarify that 
Then I saw this question in stack overflow : https://stackoverflow.com/questions/43986386/unit-testing-redux-async-actions/59655786#59655786
Related to this issue https://github.com/pburtchaell/redux-promise-middleware/issues/155
The problem in the code inside the issue that it doesn't returns the inner dispatch
> Added note about returning the inner dispatch

- README.md
The previous link to 5.0.1 was broken. Changing to 5.1.1 seems to fix it.
> Fix link to 5.x documentation in README.md
